services:
  mysql:
    image: mysql:8.0
    container_name: htap-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    command:
      - --default-authentication-plugin=mysql_native_password
      - --log_bin_trust_function_creators=ON
      - --enforce_gtid_consistency=ON
      - --gtid_mode=ON
      - --binlog_expire_logs_seconds=7200
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  mysql-setup:
    image: mysql:8.0
    container_name: htap-mysql-setup
    command: >
      sh -c "
              mysql -h mysql -u root -e \"create database test;\"
              mysql -h mysql -u root -e \"create table test.test (id bigint primary key, s varchar(100), i int);\"
              mysql -h mysql -u root -e \"insert into test.test values (1, 'a', 11), (2, 'b', 22);\"
             "
    restart: "on-failure"
    depends_on:
      mysql:
        condition: service_healthy

  myduck:
    image: apecloud/myduckserver:latest
    pull_policy: always
    container_name: htap-myduck
    environment:
      SETUP_MODE: REPLICA
      SOURCE_DSN: mysql://root@mysql:3306
    depends_on:
      mysql:
        condition: service_healthy
      mysql-setup:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "mysqlsh", "-h", "localhost", "-P", "3306", "-u", "root", "--no-password", "-e", "SELECT VERSION();"]
      interval: 5s
      timeout: 5s
      retries: 10

  create-account:
    image: mysql:8
    container_name: htap-create-account
    command: >
      sh -c "
              mysql -h mysql -u root -e \"create user 'lol'@'%' identified with 'mysql_native_password' by 'lol'; grant all privileges on *.* to 'lol'@'%';\"
             "
    restart: "on-failure"
    depends_on:
      mysql:
        condition: service_healthy
      mysql-setup:
        condition: service_completed_successfully
      myduck:
        condition: service_healthy

  maxscale:
    image: mariadb/maxscale:24.02
    container_name: maxscale
    ports:
      - "14000:4000"
      - "8989:8989"
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf.d/my-maxscale.cnf
    depends_on:
      mysql:
        condition: service_healthy
      mysql-setup:
        condition: service_completed_successfully
      myduck:
        condition: service_healthy
      create-account:
        condition: service_completed_successfully
