package transpiler

import (
	"fmt"
	"strings"
	"sync"
	"testing"
)

func TestTranslate(t *testing.T) {

	// Define a slice of test cases
	testCases := []struct {
		name     string
		input    string
		expected string
	}{

		{
			name:     "Simple CREATE TABLE with AUTO_INCREMENT",
			input:    "CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY)",
			expected: "CREATE TABLE users (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY)",
		},
		{
			name:     "CREATE TABLE without AUTO_INCREMENT",
			input:    "CREATE TABLE orders (order_id INT PRIMARY KEY)",
			expected: "CREATE TABLE orders (order_id INT PRIMARY KEY)",
		},
		{
			name:     "CREATE TABLE with multiple columns",
			input:    "CREATE TABLE products (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255))",
			expected: "CREATE TABLE products (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name TEXT(255))",
		},
		{
			name:     "CREATE TABLE with foreign key",
			input:    "CREATE TABLE orders (order_id INT PRIMARY KEY, user_id INT, FOREIGN KEY (user_id) REFERENCES users(id))",
			expected: "CREATE TABLE orders (order_id INT PRIMARY KEY, user_id INT, FOREIGN KEY (user_id) REFERENCES users (id))",
		},
		{
			name:     "SELECT with newlines",
			input:    "SELECT '\n' FROM users WHERE id = 1\n",
			expected: "SELECT '\n' FROM users WHERE id = 1",
		},
		{
			name:     "multiple statements",
			input:    "CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY); \n SELECT * FROM users WHERE id = 1",
			expected: "CREATE TABLE users (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY)",
		},
		{
			name:     "XOR expands to DuckDB boolean form",
			input:    "SELECT i FROM t WHERE i XOR i",
			expected: "SELECT i FROM t WHERE ((i) AND NOT (i)) OR (NOT (i) AND (i))",
		},
		{
			name:     "nested XOR does not emit XOR keyword",
			input:    "SELECT i XOR i XOR i FROM t",
			expected: "SELECT (((i AND (NOT i)) OR ((NOT i) AND i)) AND NOT (i)) OR (NOT ((i AND (NOT i)) OR ((NOT i) AND i)) AND (i)) FROM t",
		},
		{
			name:     "CHAR_LENGTH becomes DuckDB LENGTH",
			input:    "SELECT CHAR_LENGTH(s) FROM t",
			expected: "SELECT LENGTH(s) FROM t",
		},
		{
			name:     "CHAR_LENGTH inside AVG does not emit CHAR_LENGTH",
			input:    "SELECT FLOOR(i), AVG(CHAR_LENGTH(s)) FROM mytable mt GROUP BY 1 ORDER BY FLOOR(i) DESC",
			expected: "SELECT FLOOR(i), AVG(LENGTH(s)) FROM mytable AS mt GROUP BY 1 ORDER BY FLOOR(i) DESC",
		},
		{
			name:     "FORMAT two-arg uses DuckDB fmt grouping",
			input:    "SELECT FORMAT(i, 3) FROM mytable",
			expected: "SELECT FORMAT('{:,.3f}', i) FROM mytable",
		},
		{
			name:     "FORMAT with da_DK swaps grouping separators",
			input:    "SELECT FORMAT(i, 3, 'da_DK') FROM mytable",
			expected: "SELECT REPLACE(REPLACE(REPLACE(FORMAT('{:,.3f}', i), ',', '\x01'), '.', ','), '\x01', '.') FROM mytable",
		},
		{
			name:     "aggregate without GROUP BY wraps non-agg columns",
			input:    "SELECT pk1, SUM(c1) FROM two_pk WHERE pk1 = 0",
			expected: "SELECT ANY_VALUE(pk1), SUM(c1) FROM two_pk WHERE pk1 = 0",
		},
		{
			name:     "explicit GROUP BY is left alone",
			input:    "SELECT pk1, SUM(c1) FROM two_pk GROUP BY pk1",
			expected: "SELECT pk1, SUM(c1) FROM two_pk GROUP BY pk1",
		},
	}

	// Loop over each test case
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result, err := TranslateWithSQLGlot(tc.input)
			if err != nil {
				t.Errorf("translate(%q) returned an error: %v", tc.input, err)
			}

			trimmedResult := strings.TrimSpace(result)
			fmt.Println("trimmedResult:", trimmedResult)
			if trimmedResult != tc.expected {
				t.Errorf("translate(%q) = %v; want %v", tc.input, trimmedResult, tc.expected)
			}
		})
	}
}

func TestTranslateConcurrent(t *testing.T) {
	concurrency := 1000
	wg := sync.WaitGroup{}
	wg.Add(concurrency)

	for i := 0; i < concurrency; i++ {
		go func(i int) {
			defer wg.Done()

			sql := fmt.Sprintf("SELECT * FROM users WHERE id = %d", i)
			expectedSQL := sql

			translatedSQL, err := TranslateWithSQLGlot(sql)
			if err != nil {
				t.Errorf("translate(%q) returned an error: %v", sql, err)
			}
			if translatedSQL != expectedSQL {
				t.Errorf("translate(%q) = %v; want %v", sql, translatedSQL, expectedSQL)
			}
		}(i)
	}

	wg.Wait()
}
