package transpiler

import (
	"fmt"
	"strings"
	"sync"
	"testing"
)

func TestTranslate(t *testing.T) {

	// Define a slice of test cases
	testCases := []struct {
		name     string
		input    string
		expected string
	}{

		{
			name:     "Simple CREATE TABLE with AUTO_INCREMENT",
			input:    "CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY)",
			expected: "CREATE TABLE users (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY)",
		},
		{
			name:     "CREATE TABLE without AUTO_INCREMENT",
			input:    "CREATE TABLE orders (order_id INT PRIMARY KEY)",
			expected: "CREATE TABLE orders (order_id INT PRIMARY KEY)",
		},
		{
			name:     "CREATE TABLE with multiple columns",
			input:    "CREATE TABLE products (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255))",
			expected: "CREATE TABLE products (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name TEXT(255))",
		},
		{
			name:     "CREATE TABLE with foreign key",
			input:    "CREATE TABLE orders (order_id INT PRIMARY KEY, user_id INT, FOREIGN KEY (user_id) REFERENCES users(id))",
			expected: "CREATE TABLE orders (order_id INT PRIMARY KEY, user_id INT, FOREIGN KEY (user_id) REFERENCES users (id))",
		},
		{
			name:     "SELECT with newlines",
			input:    "SELECT '\n' FROM users WHERE id = 1\n",
			expected: "SELECT '\n' FROM users WHERE id = 1",
		},
		{
			name:     "multiple statements",
			input:    "CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY); \n SELECT * FROM users WHERE id = 1",
			expected: "CREATE TABLE users (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY)",
		},
		{
			name:     "XOR expands to DuckDB boolean form",
			input:    "SELECT i FROM t WHERE i XOR i",
			expected: "SELECT i FROM t WHERE ((i) AND NOT (i)) OR (NOT (i) AND (i))",
		},
		{
			name:     "nested XOR does not emit XOR keyword",
			input:    "SELECT i XOR i XOR i FROM t",
			expected: "SELECT (((i AND (NOT i)) OR ((NOT i) AND i)) AND NOT (i)) OR (NOT ((i AND (NOT i)) OR ((NOT i) AND i)) AND (i)) FROM t",
		},
		{
			name:     "CHAR_LENGTH becomes DuckDB LENGTH",
			input:    "SELECT CHAR_LENGTH(s) FROM t",
			expected: "SELECT LENGTH(s) FROM t",
		},
		{
			name:     "CHAR_LENGTH inside AVG does not emit CHAR_LENGTH",
			input:    "SELECT FLOOR(i), AVG(CHAR_LENGTH(s)) FROM mytable mt GROUP BY 1 ORDER BY FLOOR(i) DESC",
			expected: "SELECT FLOOR(i), AVG(LENGTH(s)) FROM mytable AS mt GROUP BY 1 ORDER BY FLOOR(i) DESC",
		},
		{
			name:     "FORMAT two-arg uses DuckDB fmt grouping",
			input:    "SELECT FORMAT(i, 3) FROM mytable",
			expected: "SELECT FORMAT('{:,.3f}', i) FROM mytable",
		},
		{
			name:     "FORMAT with da_DK swaps grouping separators",
			input:    "SELECT FORMAT(i, 3, 'da_DK') FROM mytable",
			expected: "SELECT REPLACE(REPLACE(REPLACE(FORMAT('{:,.3f}', i), ',', '\x01'), '.', ','), '\x01', '.') FROM mytable",
		},
		{
			name:     "aggregate without GROUP BY wraps non-agg columns",
			input:    "SELECT pk1, SUM(c1) FROM two_pk WHERE pk1 = 0",
			expected: "SELECT ANY_VALUE(pk1), SUM(c1) FROM two_pk WHERE pk1 = 0",
		},
		{
			name:     "explicit GROUP BY is left alone",
			input:    "SELECT pk1, SUM(c1) FROM two_pk GROUP BY pk1",
			expected: "SELECT pk1, SUM(c1) FROM two_pk GROUP BY pk1",
		},
		{
			name:     "FIND_IN_SET becomes list_position",
			input:    "SELECT FIND_IN_SET(s, 'first_row,second_row,third_row') FROM mytable",
			expected: "SELECT COALESCE(LIST_POSITION(STRING_SPLIT('first_row,second_row,third_row', ','), s), 0) FROM mytable",
		},
		{
			name:     "SUBSTRING_INDEX positive count",
			input:    "SELECT SUBSTRING_INDEX(s, 'd', 1) FROM mytable",
			expected: "SELECT CASE WHEN 1 = 0 THEN '' WHEN 1 > 0 THEN ARRAY_TO_STRING(LIST_SLICE(STRING_SPLIT(s, 'd'), 1, 1), 'd') ELSE ARRAY_TO_STRING(LIST_SLICE(STRING_SPLIT(s, 'd'), LEN(STRING_SPLIT(s, 'd')) + 1 + 1, LEN(STRING_SPLIT(s, 'd'))), 'd') END FROM mytable",
		},
		{
			name:     "HOUR casts datetime string to timestamp",
			input:    "SELECT HOUR('2007-12-11 20:21:22') FROM mytable",
			expected: "SELECT HOUR(CAST('2007-12-11 20:21:22' AS TIMESTAMP)) FROM mytable",
		},
		{
			name:     "ELT becomes list_extract",
			input:    "SELECT ELT(i, 'a', 'b') FROM mytable",
			expected: "SELECT LIST_EXTRACT(['a', 'b'], i) FROM mytable",
		},
		{
			name:     "FIELD becomes list_position",
			input:    "SELECT FIELD(i, '1', '2', '3') FROM mytable",
			expected: "SELECT COALESCE(LIST_POSITION(['1', '2', '3'], i), 0) FROM mytable",
		},
		{
			name:     "ADDDATE interval becomes date plus interval",
			input:    "SELECT ADDDATE(da, INTERVAL 1 DAY) FROM typestable",
			expected: "SELECT da + INTERVAL '1' DAY FROM typestable",
		},
		{
			name:     "ADDDATE days becomes date plus interval day",
			input:    "SELECT ADDDATE(da, 1) FROM typestable",
			expected: "SELECT da + INTERVAL 1 DAY FROM typestable",
		},
		{
			name:     "CONV 10 to 2 uses fmt binary",
			input:    "SELECT CONV(i, 10, 2) FROM mytable",
			expected: "SELECT FORMAT('{:b}', i) FROM mytable",
		},
		{
			name:     "BIT_LENGTH is octet_length times 8",
			input:    "SELECT BIT_LENGTH(i) FROM mytable",
			expected: "SELECT OCTET_LENGTH(CAST(i AS TEXT)) * 8 FROM mytable",
		},
		{
			name:     "OCTET_LENGTH becomes octet_length",
			input:    "SELECT OCTET_LENGTH(s) FROM mytable",
			expected: "SELECT OCTET_LENGTH(s) FROM mytable",
		},
		{
			name:     "OCTET_LENGTH keeps UTF-8 as bytes",
			input:    "SELECT OCTET_LENGTH('中') FROM mytable",
			expected: "SELECT OCTET_LENGTH('中') FROM mytable",
		},
		{
			name:     "UNHEX becomes from_hex",
			input:    "SELECT UNHEX(s) FROM mytable",
			expected: "SELECT FROM_HEX(s) FROM mytable",
		},
		{
			name:     "MD5 casts integers to text",
			input:    "SELECT MD5(i) FROM mytable",
			expected: "SELECT MD5(CAST(i AS TEXT)) FROM mytable",
		},
		{
			name:     "SHA2 256 becomes sha256 of text",
			input:    "SELECT SHA2(i, 256) FROM mytable",
			expected: "SELECT SHA256(CAST(i AS TEXT)) FROM mytable",
		},
		{
			name:     "ASCII is first byte",
			input:    "SELECT ASCII(s) FROM mytable",
			expected: "SELECT GET_BYTE(CAST(s AS BLOB), 0) FROM mytable",
		},
		{
			name:     "CHAR concatenates chr of each arg",
			input:    "SELECT CHAR(i, i + 10) FROM mytable",
			expected: "SELECT CONCAT(CHR(i), CHR(i + 10)) FROM mytable",
		},
		{
			name:     "JSON_PRETTY casts to JSON",
			input:    "SELECT JSON_PRETTY(c3) FROM jsontable",
			expected: "SELECT JSON_PRETTY(CAST(c3 AS JSON)) FROM jsontable",
		},
		{
			name:     "DAYOFYEAR compact date gets dashes",
			input:    "SELECT DAYOFYEAR('20071211') FROM mytable",
			expected: "SELECT DAYOFYEAR(CAST('2007-12-11' AS DATE)) FROM mytable",
		},
		{
			name:     "JSON_MERGE becomes json_merge_patch",
			input:    "SELECT JSON_MERGE(c3, '{\"a\": 1}') FROM jsontable",
			expected: "SELECT JSON_MERGE_PATCH(CAST(c3 AS JSON), CAST('{\"a\": 1}' AS JSON)) FROM jsontable",
		},
		{
			name:     "TIME_FORMAT becomes strftime",
			input:    "SELECT TIME_FORMAT(time_col, '%h%p') FROM datetime_table",
			expected: "SELECT STRFTIME(CAST(time_col AS TIMESTAMP), '%I%p') FROM datetime_table",
		},
		{
			name:     "SPACE becomes REPEAT",
			input:    "SELECT SPACE(i) FROM mytable",
			expected: "SELECT REPEAT(' ', CAST(i AS BIGINT)) FROM mytable",
		},
		{
			name:     "FROM_UNIXTIME becomes TO_TIMESTAMP",
			input:    "SELECT FROM_UNIXTIME(i) FROM mytable",
			expected: "SELECT TO_TIMESTAMP(i) FROM mytable",
		},
		{
			name:     "MOD becomes percent",
			input:    "SELECT MOD(i, 2) FROM mytable",
			expected: "SELECT i % 2 FROM mytable",
		},
		{
			name:     "JSON_OVERLAPS becomes json_contains either way",
			input:    "SELECT JSON_OVERLAPS(c3, '{\"a\": 2}') FROM jsontable",
			expected: "SELECT JSON_CONTAINS(CAST(c3 AS JSON), CAST('{\"a\": 2}' AS JSON)) OR JSON_CONTAINS(CAST('{\"a\": 2}' AS JSON), CAST(c3 AS JSON)) FROM jsontable",
		},
		{
			name:     "GREATEST is null-safe",
			input:    "SELECT GREATEST(i, s) FROM mytable",
			expected: "SELECT CASE WHEN i IS NULL OR s IS NULL THEN NULL ELSE GREATEST(i, s) END FROM mytable",
		},
		{
			name:     "LEAST is null-safe",
			input:    "SELECT LEAST(i, s) FROM mytable",
			expected: "SELECT CASE WHEN i IS NULL OR s IS NULL THEN NULL ELSE LEAST(i, s) END FROM mytable",
		},
		{
			name:     "LOCATE with start uses strpos of substring",
			input:    "SELECT LOCATE(UPPER('roW'), UPPER(s), POWER(10, 0)) FROM mytable",
			expected: "SELECT CASE WHEN STRPOS(SUBSTRING(UPPER(s), POWER(10, 0)), UPPER('roW')) = 0 THEN 0 ELSE STRPOS(SUBSTRING(UPPER(s), POWER(10, 0)), UPPER('roW')) + (POWER(10, 0)) - 1 END FROM mytable",
		},
		{
			name:     "LOG2 becomes LOG base 2",
			input:    "SELECT LOG2(i) FROM mytable",
			expected: "SELECT LOG(2, i) FROM mytable",
		},
		{
			name:     "ATAN2 is kept",
			input:    "SELECT ATAN(i), ATAN2(i, i + 2) FROM mytable",
			expected: "SELECT ATAN(i), ATAN2(i, i + 2) FROM mytable",
		},
		{
			name:     "TRIM remstr FROM str becomes trim(str, remstr)",
			input:    "SELECT TRIM(s FROM 'first row') AS s FROM mytable",
			expected: "SELECT TRIM('first row', s) AS s FROM mytable",
		},
		{
			name:     "GROUP BY wraps non-grouped columns",
			input:    "SELECT s, i FROM mytable GROUP BY i",
			expected: "SELECT ANY_VALUE(s), i FROM mytable GROUP BY i",
		},
		{
			name:     "DATETIME string becomes timestamp cast",
			input:    "SELECT DATETIME('2020-01-01T12:00:00')",
			expected: "SELECT CAST('2020-01-01T12:00:00' AS TIMESTAMP)",
		},
		{
			name:     "CAST negative AS UNSIGNED wraps",
			input:    "SELECT CAST(-3 AS UNSIGNED) FROM mytable",
			expected: "SELECT CAST(CASE WHEN -3 < 0 THEN -3 + 18446744073709551616 ELSE -3 END AS UBIGINT) FROM mytable",
		},
		{
			name:     "JSON_MERGE_PRESERVE concatenates arrays",
			input:    "SELECT JSON_MERGE_PRESERVE(c3, '{\"a\": 1}') FROM jsontable",
			expected: "SELECT CASE WHEN JSON_TYPE(CAST(c3 AS JSON)) = 'ARRAY' AND JSON_TYPE(CAST('{\"a\": 1}' AS JSON)) = 'ARRAY' THEN TO_JSON(LIST_CONCAT(JSON_EXTRACT(CAST(c3 AS JSON), '$'), JSON_EXTRACT(CAST('{\"a\": 1}' AS JSON), '$'))) ELSE JSON_MERGE_PATCH(CAST(c3 AS JSON), CAST('{\"a\": 1}' AS JSON)) END FROM jsontable",
		},
		{
			name:     "DATE_FORMAT percent-D is day ordinal",
			input:    "SELECT DATE_FORMAT(datetime_col, '%D') FROM datetime_table",
			expected: "SELECT CONCAT(CAST(DAY(CAST(datetime_col AS TIMESTAMP)) AS TEXT), CASE WHEN DAY(CAST(datetime_col AS TIMESTAMP)) IN (11, 12, 13) THEN 'th' ELSE CASE MOD(DAY(CAST(datetime_col AS TIMESTAMP)), 10) WHEN 1 THEN 'st' WHEN 2 THEN 'nd' WHEN 3 THEN 'rd' ELSE 'th' END END) FROM datetime_table",
		},
		{
			name:     "HAVING uses SELECT alias expression",
			input:    "SELECT i, 1 AS foo, 2 AS bar FROM MyTable HAVING bar = 2",
			expected: "SELECT i, 1 AS foo, 2 AS bar FROM MyTable HAVING 2 = 2",
		},
		{
			name:     "string WHERE predicate is numeric nonzero",
			input:    "SELECT i FROM mytable WHERE 'hello'",
			expected: "SELECT i FROM mytable WHERE COALESCE(TRY_CAST('hello' AS DOUBLE), 0) <> 0",
		},
		{
			name:     "NOT string predicate is numeric zero",
			input:    "SELECT i FROM mytable WHERE NOT 'hello'",
			expected: "SELECT i FROM mytable WHERE COALESCE(TRY_CAST('hello' AS DOUBLE), 0) = 0",
		},
	}

	// Loop over each test case
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result, err := TranslateWithSQLGlot(tc.input)
			if err != nil {
				t.Errorf("translate(%q) returned an error: %v", tc.input, err)
			}

			trimmedResult := strings.TrimSpace(result)
			fmt.Println("trimmedResult:", trimmedResult)
			if trimmedResult != tc.expected {
				t.Errorf("translate(%q) = %v; want %v", tc.input, trimmedResult, tc.expected)
			}
		})
	}
}

func TestTranslateConcurrent(t *testing.T) {
	concurrency := 1000
	wg := sync.WaitGroup{}
	wg.Add(concurrency)

	for i := 0; i < concurrency; i++ {
		go func(i int) {
			defer wg.Done()

			sql := fmt.Sprintf("SELECT * FROM users WHERE id = %d", i)
			expectedSQL := sql

			translatedSQL, err := TranslateWithSQLGlot(sql)
			if err != nil {
				t.Errorf("translate(%q) returned an error: %v", sql, err)
			}
			if translatedSQL != expectedSQL {
				t.Errorf("translate(%q) = %v; want %v", sql, translatedSQL, expectedSQL)
			}
		}(i)
	}

	wg.Wait()
}
