package transpiler

import (
	"fmt"
	"strings"
	"sync"
	"testing"
)

func TestTranslate(t *testing.T) {

	// Define a slice of test cases
	testCases := []struct {
		name     string
		input    string
		expected string
	}{

		{
			name:     "Simple CREATE TABLE with AUTO_INCREMENT",
			input:    "CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY)",
			expected: "CREATE TABLE users (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY)",
		},
		{
			name:     "CREATE TABLE without AUTO_INCREMENT",
			input:    "CREATE TABLE orders (order_id INT PRIMARY KEY)",
			expected: "CREATE TABLE orders (order_id INT PRIMARY KEY)",
		},
		{
			name:     "CREATE TABLE with multiple columns",
			input:    "CREATE TABLE products (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255))",
			expected: "CREATE TABLE products (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name TEXT(255))",
		},
		{
			name:     "CREATE TABLE with foreign key",
			input:    "CREATE TABLE orders (order_id INT PRIMARY KEY, user_id INT, FOREIGN KEY (user_id) REFERENCES users(id))",
			expected: "CREATE TABLE orders (order_id INT PRIMARY KEY, user_id INT, FOREIGN KEY (user_id) REFERENCES users (id))",
		},
		{
			name:     "SELECT with newlines",
			input:    "SELECT '\n' FROM users WHERE id = 1\n",
			expected: "SELECT '\n' FROM users WHERE id = 1",
		},
		{
			name:     "multiple statements",
			input:    "CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY); \n SELECT * FROM users WHERE id = 1",
			expected: "CREATE TABLE users (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY)",
		},
		{
			name:     "XOR expands to DuckDB boolean form",
			input:    "SELECT i FROM t WHERE i XOR i",
			expected: "SELECT i FROM t WHERE ((i) AND NOT (i)) OR (NOT (i) AND (i))",
		},
		{
			name:     "nested XOR does not emit XOR keyword",
			input:    "SELECT i XOR i XOR i FROM t",
			expected: "SELECT (((i AND (NOT i)) OR ((NOT i) AND i)) AND NOT (i)) OR (NOT ((i AND (NOT i)) OR ((NOT i) AND i)) AND (i)) FROM t",
		},
		{
			name:     "parenthesized JOIN without ON becomes CROSS JOIN",
			input:    "SELECT * FROM (ab JOIN pq) WHERE a IN (SELECT a FROM ab)",
			expected: "SELECT * FROM (ab CROSS JOIN pq) WHERE a IN (SELECT a FROM ab)",
		},
		{
			name:     "CHAR_LENGTH becomes DuckDB LENGTH",
			input:    "SELECT CHAR_LENGTH(s) FROM t",
			expected: "SELECT LENGTH(s) FROM t",
		},
		{
			name:     "CHAR_LENGTH inside AVG does not emit CHAR_LENGTH",
			input:    "SELECT FLOOR(i), AVG(CHAR_LENGTH(s)) FROM mytable mt GROUP BY 1 ORDER BY FLOOR(i) DESC",
			expected: "SELECT FLOOR(i), AVG(LENGTH(s)) FROM mytable AS mt GROUP BY 1 ORDER BY FLOOR(i) DESC",
		},
		{
			name:     "FORMAT two-arg uses DuckDB fmt grouping",
			input:    "SELECT FORMAT(i, 3) FROM mytable",
			expected: "SELECT FORMAT('{:,.3f}', i) FROM mytable",
		},
		{
			name:     "FORMAT with da_DK swaps grouping separators",
			input:    "SELECT FORMAT(i, 3, 'da_DK') FROM mytable",
			expected: "SELECT REPLACE(REPLACE(REPLACE(FORMAT('{:,.3f}', i), ',', '\x01'), '.', ','), '\x01', '.') FROM mytable",
		},
		{
			name:     "aggregate without GROUP BY wraps non-agg columns",
			input:    "SELECT pk1, SUM(c1) FROM two_pk WHERE pk1 = 0",
			expected: "SELECT ANY_VALUE(pk1), SUM(c1) FROM two_pk WHERE pk1 = 0",
		},
		{
			name:     "aggregate leaves constant select items unwrapped",
			input:    "SELECT count(*), i, concat(i, i), 123, 'abc', concat('abc', 'def') FROM emptytable",
			expected: "SELECT COUNT(*), ANY_VALUE(i), ANY_VALUE(i || i), 123, 'abc', 'abc' || 'def' FROM emptytable",
		},
		{
			name:     "explicit GROUP BY is left alone",
			input:    "SELECT pk1, SUM(c1) FROM two_pk GROUP BY pk1",
			expected: "SELECT pk1, SUM(c1) FROM two_pk GROUP BY pk1",
		},
		{
			name:     "FIND_IN_SET becomes list_position",
			input:    "SELECT FIND_IN_SET(s, 'first_row,second_row,third_row') FROM mytable",
			expected: "SELECT COALESCE(LIST_POSITION(STRING_SPLIT('first_row,second_row,third_row', ','), s), 0) FROM mytable",
		},
		{
			name:     "SUBSTRING_INDEX positive count",
			input:    "SELECT SUBSTRING_INDEX(s, 'd', 1) FROM mytable",
			expected: "SELECT CASE WHEN 1 = 0 THEN '' WHEN 1 > 0 THEN ARRAY_TO_STRING(LIST_SLICE(STRING_SPLIT(s, 'd'), 1, 1), 'd') ELSE ARRAY_TO_STRING(LIST_SLICE(STRING_SPLIT(s, 'd'), LEN(STRING_SPLIT(s, 'd')) + 1 + 1, LEN(STRING_SPLIT(s, 'd'))), 'd') END FROM mytable",
		},
		{
			name:     "HOUR casts datetime string to timestamp",
			input:    "SELECT HOUR('2007-12-11 20:21:22') FROM mytable",
			expected: "SELECT HOUR(CAST('2007-12-11 20:21:22' AS TIMESTAMP)) FROM mytable",
		},
		{
			name:     "ELT becomes list_extract",
			input:    "SELECT ELT(i, 'a', 'b') FROM mytable",
			expected: "SELECT LIST_EXTRACT(['a', 'b'], i) FROM mytable",
		},
		{
			name:     "FIELD becomes list_position",
			input:    "SELECT FIELD(i, '1', '2', '3') FROM mytable",
			expected: "SELECT COALESCE(LIST_POSITION(['1', '2', '3'], i), 0) FROM mytable",
		},
		{
			name:     "ADDDATE interval becomes date plus interval",
			input:    "SELECT ADDDATE(da, INTERVAL 1 DAY) FROM typestable",
			expected: "SELECT da + INTERVAL '1' DAY FROM typestable",
		},
		{
			name:     "ADDDATE days becomes date plus interval day",
			input:    "SELECT ADDDATE(da, 1) FROM typestable",
			expected: "SELECT da + INTERVAL 1 DAY FROM typestable",
		},
		{
			name:     "CONV 10 to 2 uses fmt binary",
			input:    "SELECT CONV(i, 10, 2) FROM mytable",
			expected: "SELECT FORMAT('{:b}', i) FROM mytable",
		},
		{
			name:     "BIT_LENGTH is octet_length times 8",
			input:    "SELECT BIT_LENGTH(i) FROM mytable",
			expected: "SELECT OCTET_LENGTH(CAST(i AS TEXT)) * 8 FROM mytable",
		},
		{
			name:     "OCTET_LENGTH becomes octet_length",
			input:    "SELECT OCTET_LENGTH(s) FROM mytable",
			expected: "SELECT OCTET_LENGTH(s) FROM mytable",
		},
		{
			name:     "OCTET_LENGTH keeps UTF-8 as bytes",
			input:    "SELECT OCTET_LENGTH('中') FROM mytable",
			expected: "SELECT OCTET_LENGTH('中') FROM mytable",
		},
		{
			name:     "UNHEX becomes from_hex",
			input:    "SELECT UNHEX(s) FROM mytable",
			expected: "SELECT FROM_HEX(s) FROM mytable",
		},
		{
			name:     "MD5 casts integers to text",
			input:    "SELECT MD5(i) FROM mytable",
			expected: "SELECT MD5(CAST(i AS TEXT)) FROM mytable",
		},
		{
			name:     "SHA2 256 becomes sha256 of text",
			input:    "SELECT SHA2(i, 256) FROM mytable",
			expected: "SELECT SHA256(CAST(i AS TEXT)) FROM mytable",
		},
		{
			name:     "ASCII is first byte",
			input:    "SELECT ASCII(s) FROM mytable",
			expected: "SELECT GET_BYTE(CAST(s AS BLOB), 0) FROM mytable",
		},
		{
			name:     "CHAR concatenates chr of each arg",
			input:    "SELECT CHAR(i, i + 10) FROM mytable",
			expected: "SELECT CONCAT(CHR(i), CHR(i + 10)) FROM mytable",
		},
		{
			name:     "JSON_PRETTY casts to JSON",
			input:    "SELECT JSON_PRETTY(c3) FROM jsontable",
			expected: "SELECT JSON_PRETTY(CAST(c3 AS JSON)) FROM jsontable",
		},
		{
			name:     "DAYOFYEAR compact date gets dashes",
			input:    "SELECT DAYOFYEAR('20071211') FROM mytable",
			expected: "SELECT DAYOFYEAR(CAST('2007-12-11' AS DATE)) FROM mytable",
		},
		{
			name:     "JSON_MERGE becomes json_merge_patch",
			input:    "SELECT JSON_MERGE(c3, '{\"a\": 1}') FROM jsontable",
			expected: "SELECT JSON_MERGE_PATCH(CAST(c3 AS JSON), CAST('{\"a\": 1}' AS JSON)) FROM jsontable",
		},
		{
			name:     "TIME_FORMAT becomes strftime",
			input:    "SELECT TIME_FORMAT(time_col, '%h%p') FROM datetime_table",
			expected: "SELECT STRFTIME(CAST(time_col AS TIMESTAMP), '%I%p') FROM datetime_table",
		},
		{
			name:     "SPACE becomes REPEAT",
			input:    "SELECT SPACE(i) FROM mytable",
			expected: "SELECT REPEAT(' ', CAST(i AS BIGINT)) FROM mytable",
		},
		{
			name:     "FROM_UNIXTIME becomes TO_TIMESTAMP",
			input:    "SELECT FROM_UNIXTIME(i) FROM mytable",
			expected: "SELECT TO_TIMESTAMP(i) FROM mytable",
		},
		{
			name:     "MOD becomes percent",
			input:    "SELECT MOD(i, 2) FROM mytable",
			expected: "SELECT i % 2 FROM mytable",
		},
		{
			name:     "JSON_OVERLAPS becomes json_contains either way",
			input:    "SELECT JSON_OVERLAPS(c3, '{\"a\": 2}') FROM jsontable",
			expected: "SELECT JSON_CONTAINS(CAST(c3 AS JSON), CAST('{\"a\": 2}' AS JSON)) OR JSON_CONTAINS(CAST('{\"a\": 2}' AS JSON), CAST(c3 AS JSON)) FROM jsontable",
		},
		{
			name:     "GREATEST is null-safe",
			input:    "SELECT GREATEST(i, s) FROM mytable",
			expected: "SELECT CASE WHEN i IS NULL OR s IS NULL THEN NULL ELSE GREATEST(i, s) END FROM mytable",
		},
		{
			name:     "LEAST is null-safe",
			input:    "SELECT LEAST(i, s) FROM mytable",
			expected: "SELECT CASE WHEN i IS NULL OR s IS NULL THEN NULL ELSE LEAST(i, s) END FROM mytable",
		},
		{
			name:     "LOCATE with start uses strpos of substring",
			input:    "SELECT LOCATE(UPPER('roW'), UPPER(s), POWER(10, 0)) FROM mytable",
			expected: "SELECT CASE WHEN STRPOS(SUBSTRING(UPPER(s), POWER(10, 0)), UPPER('roW')) = 0 THEN 0 ELSE STRPOS(SUBSTRING(UPPER(s), POWER(10, 0)), UPPER('roW')) + (POWER(10, 0)) - 1 END FROM mytable",
		},
		{
			name:     "LOG2 becomes LOG base 2",
			input:    "SELECT LOG2(i) FROM mytable",
			expected: "SELECT LOG(2, i) FROM mytable",
		},
		{
			name:     "ATAN2 is kept",
			input:    "SELECT ATAN(i), ATAN2(i, i + 2) FROM mytable",
			expected: "SELECT ATAN(i), ATAN2(i, i + 2) FROM mytable",
		},
		{
			name:     "TRIM remstr FROM str becomes trim(str, remstr)",
			input:    "SELECT TRIM(s FROM 'first row') AS s FROM mytable",
			expected: "SELECT TRIM('first row', s) AS s FROM mytable",
		},
		{
			name:     "GROUP BY wraps non-grouped columns",
			input:    "SELECT s, i FROM mytable GROUP BY i",
			expected: "SELECT ANY_VALUE(s), i FROM mytable GROUP BY i",
		},
		{
			name:     "DATETIME string becomes timestamp cast",
			input:    "SELECT DATETIME('2020-01-01T12:00:00')",
			expected: "SELECT CAST('2020-01-01T12:00:00' AS TIMESTAMP)",
		},
		{
			name:     "CAST negative AS UNSIGNED wraps",
			input:    "SELECT CAST(-3 AS UNSIGNED) FROM mytable",
			expected: "SELECT CAST(CASE WHEN -3 < 0 THEN -3 + 18446744073709551616 ELSE -3 END AS UBIGINT) FROM mytable",
		},
		{
			name:     "JSON_MERGE_PRESERVE concatenates arrays",
			input:    "SELECT JSON_MERGE_PRESERVE(c3, '{\"a\": 1}') FROM jsontable",
			expected: "SELECT CASE WHEN JSON_TYPE(CAST(c3 AS JSON)) = 'ARRAY' AND JSON_TYPE(CAST('{\"a\": 1}' AS JSON)) = 'ARRAY' THEN TO_JSON(LIST_CONCAT(JSON_EXTRACT(CAST(c3 AS JSON), '$'), JSON_EXTRACT(CAST('{\"a\": 1}' AS JSON), '$'))) ELSE JSON_MERGE_PATCH(CAST(c3 AS JSON), CAST('{\"a\": 1}' AS JSON)) END FROM jsontable",
		},
		{
			name:     "DATE_FORMAT percent-D is day ordinal",
			input:    "SELECT DATE_FORMAT(datetime_col, '%D') FROM datetime_table",
			expected: "SELECT CONCAT(CAST(DAY(CAST(datetime_col AS TIMESTAMP)) AS TEXT), CASE WHEN DAY(CAST(datetime_col AS TIMESTAMP)) IN (11, 12, 13) THEN 'th' ELSE CASE MOD(DAY(CAST(datetime_col AS TIMESTAMP)), 10) WHEN 1 THEN 'st' WHEN 2 THEN 'nd' WHEN 3 THEN 'rd' ELSE 'th' END END) FROM datetime_table",
		},
		{
			name:     "HAVING uses SELECT alias expression",
			input:    "SELECT i, 1 AS foo, 2 AS bar FROM MyTable HAVING bar = 2",
			expected: "SELECT i, 1 AS foo, 2 AS bar FROM MyTable HAVING 2 = 2",
		},
		{
			name:     "string WHERE predicate is numeric nonzero",
			input:    "SELECT i FROM mytable WHERE 'hello'",
			expected: "SELECT i FROM mytable WHERE COALESCE(TRY_CAST('hello' AS DOUBLE), 0) <> 0",
		},
		{
			name:     "NOT string predicate is numeric zero",
			input:    "SELECT i FROM mytable WHERE NOT 'hello'",
			expected: "SELECT i FROM mytable WHERE COALESCE(TRY_CAST('hello' AS DOUBLE), 0) = 0",
		},
		{
			name:     "bare column WHERE is numeric nonzero",
			input:    "SELECT i, v FROM stringandtable WHERE v",
			expected: "SELECT i, v FROM stringandtable WHERE CASE WHEN v IS NULL THEN NULL ELSE COALESCE(TRY_CAST(v AS DOUBLE), 0) END <> 0",
		},
		{
			name:     "string OR is numeric 0/1 for LIKE",
			input:    "SELECT c1 FROM jsontable WHERE c1 LIKE (('%' OR 'dsads') OR '%')",
			expected: "SELECT c1 FROM jsontable WHERE c1 LIKE CAST((CAST((CAST(COALESCE(TRY_CAST('%' AS DOUBLE), 0) <> 0 OR COALESCE(TRY_CAST('dsads' AS DOUBLE), 0) <> 0 AS INT)) OR COALESCE(TRY_CAST('%' AS DOUBLE), 0) <> 0 AS INT)) AS TEXT)",
		},
		{
			name:     "string OR NULL is numeric for LIKE",
			input:    "SELECT c1 FROM jsontable WHERE c1 LIKE ('%' OR NULL)",
			expected: "SELECT c1 FROM jsontable WHERE c1 LIKE CAST((CAST(COALESCE(TRY_CAST('%' AS DOUBLE), 0) <> 0 OR NULL AS INT)) AS TEXT)",
		},
		{
			name:     "numeric OR in CASE is 0/1",
			input:    "SELECT CASE 1 WHEN 2 THEN 1.0 ELSE (1||2) END",
			expected: "SELECT CASE 1 WHEN 2 THEN 1.0 ELSE (CAST(COALESCE(TRY_CAST(1 AS DOUBLE), 0) <> 0 OR COALESCE(TRY_CAST(2 AS DOUBLE), 0) <> 0 AS INT)) END",
		},
		{
			name:     "bitwise OR FALSE is 0",
			input:    "SELECT * FROM mytable WHERE (i = 1 | FALSE) IN (TRUE)",
			expected: "SELECT * FROM mytable WHERE (i = 1 | 0) IN (TRUE)",
		},
		{
			name:     "bitwise AND FALSE is 0",
			input:    "SELECT * FROM mytable WHERE (i = 1 & FALSE) IN (TRUE)",
			expected: "SELECT * FROM mytable WHERE (i = 1 & 0) IN (TRUE)",
		},
		{
			name:     "ASIN outside [-1,1] is NULL",
			input:    "SELECT ASIN(i) FROM mytable",
			expected: "SELECT CASE WHEN ABS(i) > 1 THEN NULL ELSE ASIN(i) END FROM mytable",
		},
		{
			name:     "ACOS outside [-1,1] is NULL",
			input:    "SELECT ACOS(i) FROM mytable",
			expected: "SELECT CASE WHEN ABS(i) > 1 THEN NULL ELSE ACOS(i) END FROM mytable",
		},
		{
			name:     "string column compared to number is numeric",
			input:    "SELECT s > 2 FROM tabletest",
			expected: "SELECT CASE WHEN s IS NULL THEN NULL ELSE COALESCE(TRY_CAST(s AS DOUBLE), 0) END > 2 FROM tabletest",
		},
		{
			name:     "scalar subquery MAX is not an outer aggregate",
			input:    "SELECT pk, (SELECT max(pk) FROM one_pk WHERE pk < opk.pk) AS x FROM one_pk opk",
			expected: "SELECT pk, (SELECT MAX(pk) FROM one_pk WHERE pk < opk.pk) AS x FROM one_pk AS opk",
		},
		{
			name:     "GROUP BY subquery alias wraps extra column",
			input:    "SELECT pk, (SELECT max(pk) FROM one_pk WHERE pk < opk.pk) AS x FROM one_pk opk GROUP BY x",
			expected: "SELECT ANY_VALUE(pk), (SELECT MAX(pk) FROM one_pk WHERE pk < opk.pk) AS x FROM one_pk AS opk GROUP BY x",
		},
		{
			name:     "aggregate ORDER BY unused column is dropped",
			input:    "SELECT count(*) FROM people WHERE last_name='doe' AND first_name='jane' ORDER BY dob",
			expected: "SELECT COUNT(*) FROM people WHERE last_name = 'doe' AND first_name = 'jane'",
		},
		{
			name:     "window aggregate keeps ORDER BY",
			input:    "SELECT count(*) OVER () FROM mytable ORDER BY i",
			expected: "SELECT COUNT(*) OVER () FROM mytable ORDER BY i NULLS FIRST",
		},
		{
			name:     "window functions are not outer aggregates",
			input:    "SELECT pk, row_number() OVER (ORDER BY pk DESC), SUM(v1) OVER (PARTITION BY v2 ORDER BY pk) FROM one_pk_three_idx ORDER BY pk",
			expected: "SELECT pk, ROW_NUMBER() OVER (ORDER BY pk DESC), SUM(v1) OVER (PARTITION BY v2 ORDER BY pk NULLS FIRST) FROM one_pk_three_idx ORDER BY pk NULLS FIRST",
		},
		{
			name:     "duplicate SET keeps the last assignment",
			input:    "UPDATE floattable SET f32 = 5, f32 = 4 WHERE i = 1",
			expected: "UPDATE floattable SET f32 = 4 WHERE i = 1",
		},
		{
			name:     "REPLACE INTO becomes INSERT OR REPLACE",
			input:    "REPLACE INTO mytable VALUES (1, 'first row')",
			expected: "INSERT OR REPLACE INTO mytable VALUES (1, 'first row')",
		},
		{
			name:     "INSERT IGNORE becomes INSERT OR IGNORE",
			input:    "INSERT IGNORE INTO mytable VALUES (1, 'hi')",
			expected: "INSERT OR IGNORE INTO mytable VALUES (1, 'hi')",
		},
		{
			name:     "REPLACE INTO SET becomes INSERT OR REPLACE",
			input:    "REPLACE INTO mytable SET i = 1, s = 'first row'",
			expected: "INSERT OR REPLACE INTO mytable (i, s) VALUES (1, 'first row')",
		},
		{
			name:     "later SET uses earlier assignment",
			input:    "UPDATE floattable SET f32 = f32 + f32, f64 = f32 * f64 WHERE i = 2",
			expected: "UPDATE floattable SET f32 = f32 + f32, f64 = (f32 + f32) * f64 WHERE i = 2",
		},
		{
			name:     "SET substitutes then keeps last assignment",
			input:    "UPDATE t SET a = 1, b = a, a = 2",
			expected: "UPDATE t SET b = 1, a = 2",
		},
		{
			name:     "charset introducer is stripped",
			input:    "UPDATE mytable SET s = _binary 'updated' WHERE i = 3",
			expected: "UPDATE mytable SET s = 'updated' WHERE i = 3",
		},
		{
			name:     "id = 1 is left alone",
			input:    "SELECT i FROM mytable WHERE id = 1",
			expected: "SELECT i FROM mytable WHERE id = 1",
		},
		{
			name:     "RAND seed uses mysql_rand",
			input:    "SELECT RAND(i) FROM mytable ORDER BY i",
			expected: "SELECT MYSQL_RAND(i) FROM mytable ORDER BY i NULLS FIRST",
		},
		{
			name:     "RANDOM_BYTES uses mysql_random_bytes",
			input:    "SELECT LENGTH(RANDOM_BYTES(i)) FROM mytable",
			expected: "SELECT OCTET_LENGTH(MYSQL_RANDOM_BYTES(i)) FROM mytable",
		},
		{
			name:     "string column equal to zero is numeric",
			input:    "SELECT * FROM tabletest WHERE s = 0",
			expected: "SELECT * FROM tabletest WHERE CASE WHEN s IS NULL THEN NULL ELSE COALESCE(TRY_CAST(s AS DOUBLE), 0) END = 0",
		},
		{
			name:     "CASE mixed int and string casts to text",
			input:    "SELECT CASE WHEN i > 2 THEN i ELSE 'two' END FROM mytable",
			expected: "SELECT CASE WHEN CASE WHEN i IS NULL THEN NULL ELSE COALESCE(TRY_CAST(i AS DOUBLE), 0) END > 2 THEN CAST(i AS TEXT) ELSE CAST('two' AS TEXT) END FROM mytable",
		},
		{
			name:     "FALSE IN string is numeric",
			input:    "SELECT * FROM xy INNER JOIN uv ON (xy.x IN (FALSE IN ('asdf')))",
			expected: "SELECT * FROM xy INNER JOIN uv ON (xy.x IN (CAST(0 IN (COALESCE(TRY_CAST('asdf' AS DOUBLE), 0)) AS INT)))",
		},
		{
			name:     "mixed string BETWEEN is numeric",
			input:    "SELECT * FROM mytable WHERE (i BETWEEN ('' BETWEEN '' AND ('' OR '#')) AND i)",
			expected: "SELECT * FROM mytable WHERE (i BETWEEN (CAST(COALESCE(TRY_CAST('' AS DOUBLE), 0) BETWEEN COALESCE(TRY_CAST('' AS DOUBLE), 0) AND CAST(COALESCE(TRY_CAST('' AS DOUBLE), 0) <> 0 OR COALESCE(TRY_CAST('#' AS DOUBLE), 0) <> 0 AS INT) AS INT)) AND i)",
		},
		{
			name:     "mixed IN is pairwise compare",
			input:    "SELECT COUNT(*) FROM mytable WHERE s IN (1, 'first_row')",
			expected: "SELECT COUNT(*) FROM mytable WHERE CASE WHEN s IS NULL THEN NULL ELSE COALESCE(TRY_CAST(s AS DOUBLE), 0) END = 1 OR s = 'first_row'",
		},
		{
			name:     "DATE vs ISO datetime keeps time",
			input:    "SELECT i FROM datetime_table WHERE date_col = '2019-12-31T00:00:01'",
			expected: "SELECT i FROM datetime_table WHERE date_col = CAST('2019-12-31T00:00:01' AS TIMESTAMP)",
		},
		{
			name:     "DAYNAME accepts non-dates",
			input:    "SELECT DAYNAME(i) FROM mytable",
			expected: "SELECT DAYNAME(COALESCE(TRY_CAST(i AS TIMESTAMP), TRY_STRPTIME(LPAD(TRY_CAST(i AS TEXT), 8, '0'), '%Y%m%d'))) FROM mytable",
		},
		{
			name:     "JSON_KEYS uses TRY_CAST",
			input:    "SELECT JSON_KEYS(c3) FROM jsontable",
			expected: "SELECT JSON_KEYS(TRY_CAST(c3 AS JSON)) FROM jsontable",
		},
		{
			name:     "CRC32 uses sys macro",
			input:    "SELECT CRC32(i) FROM mytable",
			expected: "SELECT __SYS__.MYSQL_CRC32(CAST(i AS TEXT)) FROM mytable",
		},
		{
			name:     "CAST AS DECIMAL is integer scale",
			input:    "SELECT DISTINCT CAST(i AS DECIMAL) FROM mytable",
			expected: "SELECT DISTINCT CAST(i AS DECIMAL(38, 0)) FROM mytable",
		},
		{
			name:     "VALUES ROW becomes VALUES tuple",
			input:    "SELECT a.column_0 FROM (VALUES ROW(1, '1'), ROW(2, '2')) a",
			expected: "SELECT a.column_0 FROM (VALUES (1, '1'), (2, '2')) AS a(column_0, column_1)",
		},
		{
			name:     "reserved word columns are quoted",
			input:    "SELECT reservedWordsTable.AND, reservedWordsTABLE.Or, reservedwordstable.SEleCT FROM reservedWordsTable",
			expected: "SELECT reservedWordsTable.\"AND\", reservedWordsTABLE.\"Or\", reservedwordstable.\"SEleCT\" FROM reservedWordsTable",
		},
		{
			name:     "tuple IN subquery becomes EXISTS",
			input:    "SELECT pk FROM one_pk WHERE (pk, 123) IN (SELECT count(*) AS u, 123 AS v FROM emptytable)",
			expected: "SELECT pk FROM one_pk WHERE EXISTS(SELECT 1 FROM (SELECT COUNT(*) AS u, 123 AS v FROM emptytable) AS q WHERE pk = q.u AND 123 = q.v)",
		},
		{
			name:     "CTE name matching table is not circular",
			input:    "WITH mytable AS (SELECT * FROM mytable) SELECT s, i FROM mytable",
			expected: "WITH mytable__mds AS (SELECT * FROM mytable) SELECT s, i FROM mytable__mds",
		},
		{
			name:     "DELETE JOIN becomes DELETE USING",
			input:    "DELETE mytable FROM mytable JOIN tabletest WHERE mytable.i = tabletest.i",
			expected: "DELETE FROM mytable USING tabletest WHERE mytable.i = tabletest.i",
		},
		{
			name:     "DELETE JOIN other target keeps USING source",
			input:    "DELETE tabletest FROM mytable JOIN tabletest WHERE mytable.i = tabletest.i",
			expected: "DELETE FROM tabletest USING mytable WHERE mytable.i = tabletest.i",
		},
		{
			name:     "DELETE JOIN alias target",
			input:    "DELETE t1 FROM mytable AS t1 JOIN tabletest WHERE t1.i = tabletest.i",
			expected: "DELETE FROM mytable AS t1 USING tabletest WHERE t1.i = tabletest.i",
		},
		{
			name:     "DELETE t FROM t is plain DELETE",
			input:    "DELETE mytable FROM mytable",
			expected: "DELETE FROM mytable",
		},
		{
			name:     "DELETE USING drops the target table",
			input:    "DELETE FROM mytable USING mytable INNER JOIN tabletest ON mytable.i = tabletest.i",
			expected: "DELETE FROM mytable USING tabletest WHERE mytable.i = tabletest.i",
		},
		{
			name:     "DELETE ORDER BY LIMIT uses rowid",
			input:    "DELETE FROM mytable ORDER BY i ASC LIMIT 2",
			expected: "DELETE FROM mytable WHERE rowid IN ((SELECT rowid FROM mytable ORDER BY i ASC NULLS FIRST LIMIT 2))",
		},
		{
			name:     "DELETE LIMIT OFFSET uses rowid",
			input:    "DELETE FROM mytable ORDER BY i DESC LIMIT 1 OFFSET 1;",
			expected: "DELETE FROM mytable WHERE rowid IN (SELECT rowid FROM mytable ORDER BY i DESC LIMIT 1 OFFSET 1)",
		},
		{
			name:     "DUAL becomes a one-row subquery",
			input:    "WITH t(n) AS (SELECT (1) FROM dual) DELETE FROM mytable WHERE i IN (SELECT n FROM t)",
			expected: "WITH t(n) AS (SELECT (1) FROM (SELECT 1) AS dual) DELETE FROM mytable WHERE i IN (SELECT n FROM t)",
		},
		{
			name:     "UPDATE JOIN becomes rowid IN",
			input:    "UPDATE mytable INNER JOIN one_pk ON mytable.i = one_pk.c5 SET mytable.i = mytable.i * 10",
			expected: "UPDATE mytable SET i = mytable.i * 10 WHERE rowid IN ((SELECT DISTINCT mytable.rowid FROM mytable INNER JOIN one_pk ON mytable.i = one_pk.c5))",
		},
		{
			name:     "UPDATE JOIN other target uses rowid",
			input:    "UPDATE one_pk INNER JOIN two_pk ON one_pk.pk = two_pk.pk1 SET two_pk.c1 = two_pk.c1 + 1",
			expected: "UPDATE two_pk SET c1 = two_pk.c1 + 1 WHERE rowid IN ((SELECT DISTINCT two_pk.rowid FROM one_pk INNER JOIN two_pk ON one_pk.pk = two_pk.pk1))",
		},
		{
			name:     "UPDATE JOIN keeps extra WHERE",
			input:    "UPDATE one_pk INNER JOIN two_pk ON one_pk.pk = two_pk.pk1 SET two_pk.c1 = two_pk.c1 + 1 WHERE one_pk.c5 < 10",
			expected: "UPDATE two_pk SET c1 = two_pk.c1 + 1 WHERE rowid IN ((SELECT DISTINCT two_pk.rowid FROM one_pk INNER JOIN two_pk ON one_pk.pk = two_pk.pk1 WHERE CASE WHEN one_pk.c5 IS NULL THEN NULL ELSE COALESCE(TRY_CAST(one_pk.c5 AS DOUBLE), 0) END < 10))",
		},
		{
			name:     "UPDATE JOIN SET from other table uses FROM",
			input:    "UPDATE one_pk INNER JOIN two_pk ON one_pk.pk = two_pk.pk1 SET one_pk.c1 = two_pk.c1 + 1",
			expected: "UPDATE one_pk SET c1 = src.__s0 FROM (SELECT one_pk.rowid AS __rid, two_pk.c1 + 1 AS __s0 FROM one_pk INNER JOIN two_pk ON one_pk.pk = two_pk.pk1 QUALIFY ROW_NUMBER() OVER (PARTITION BY one_pk.rowid) = 1) AS src WHERE rowid = src.__rid",
		},
		{
			name:     "UPDATE ORDER BY LIMIT uses rowid",
			input:    "UPDATE mytable SET s = 'updated' ORDER BY i ASC LIMIT 2",
			expected: "UPDATE mytable SET s = 'updated' WHERE rowid IN ((SELECT rowid FROM mytable ORDER BY i ASC NULLS FIRST LIMIT 2))",
		},
		{
			name:     "UPDATE LIMIT OFFSET uses rowid",
			input:    "UPDATE mytable SET s = 'updated' ORDER BY i LIMIT 1 OFFSET 1",
			expected: "UPDATE mytable SET s = 'updated' WHERE rowid IN ((SELECT rowid FROM mytable ORDER BY i NULLS FIRST LIMIT 1 OFFSET 1))",
		},
		{
			name:     "multi-table UPDATE SET is left alone",
			input:    "UPDATE one_pk INNER JOIN two_pk ON one_pk.pk = two_pk.pk1 SET one_pk.c1 = one_pk.c1 + 1, two_pk.c1 = two_pk.c2 + 1",
			expected: "UPDATE one_pk INNER JOIN two_pk ON one_pk.pk = two_pk.pk1 SET one_pk.c1 = one_pk.c1 + 1, two_pk.c1 = two_pk.c2 + 1",
		},
		{
			name:     "SELECT VALUES(col) is NULL",
			input:    "SELECT VALUES(i) FROM mytable",
			expected: "SELECT NULL FROM mytable",
		},
		{
			name:     "ON DUPLICATE KEY keeps VALUES",
			input:    "INSERT INTO mytable (i, s) VALUES (1, 'hi') ON DUPLICATE KEY UPDATE s = VALUES(s)",
			expected: "INSERT INTO mytable (i, s) VALUES (1, 'hi') ON DUPLICATE KEY UPDATE SET s = VALUES(s)",
		},
		{
			name:     "UPDATE LEFT JOIN is left alone",
			input:    "UPDATE othertable LEFT JOIN tabletest ON othertable.i2 = 3 AND tabletest.i = 3 SET othertable.s2 = 'fourth'",
			expected: "UPDATE othertable LEFT JOIN tabletest ON othertable.i2 = 3 AND tabletest.i = 3 SET othertable.s2 = 'fourth'",
		},
	}

	// Loop over each test case
	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result, err := TranslateWithSQLGlot(tc.input)
			if err != nil {
				t.Errorf("translate(%q) returned an error: %v", tc.input, err)
			}

			trimmedResult := strings.TrimSpace(result)
			fmt.Println("trimmedResult:", trimmedResult)
			if trimmedResult != tc.expected {
				t.Errorf("translate(%q) = %v; want %v", tc.input, trimmedResult, tc.expected)
			}
		})
	}
}

func TestTranslateConcurrent(t *testing.T) {
	concurrency := 1000
	wg := sync.WaitGroup{}
	wg.Add(concurrency)

	for i := 0; i < concurrency; i++ {
		go func(i int) {
			defer wg.Done()

			sql := fmt.Sprintf("SELECT * FROM users WHERE id = %d", i)
			expectedSQL := sql

			translatedSQL, err := TranslateWithSQLGlot(sql)
			if err != nil {
				t.Errorf("translate(%q) returned an error: %v", sql, err)
			}
			if translatedSQL != expectedSQL {
				t.Errorf("translate(%q) = %v; want %v", sql, translatedSQL, expectedSQL)
			}
		}(i)
	}

	wg.Wait()
}
