name: BATS Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bats-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install system packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: bats mysql-client postgresql-client
          version: 1.0

      - name: Install dependencies
        run: |
          go get .

          pip3 install "sqlglot[rs]" pyarrow pandas

          curl -LJO https://github.com/duckdb/duckdb/releases/latest/download/duckdb_cli-linux-amd64.zip
          unzip duckdb_cli-linux-amd64.zip
          chmod +x duckdb
          sudo mv duckdb /usr/local/bin

          curl -LJO https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell_9.1.0-1debian12_amd64.deb
          sudo apt-get install -y ./mysql-shell_9.1.0-1debian12_amd64.deb

      - name: Build
        run: go build -v

      - name: Start MyDuck Server
        run: |
          ./myduckserver &
          sleep 5

      - name: Run BATS Tests
        run: |
          find test/bats -name "*.bats" -type f -exec bats --print-output-on-failure {} +