name: MySQL HTAP ProxySQL Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  htap-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          curl -LJO https://github.com/duckdb/duckdb/releases/latest/download/duckdb_cli-linux-amd64.zip
          unzip duckdb_cli-linux-amd64.zip
          chmod +x duckdb
          sudo mv duckdb /usr/local/bin

      - name: Launch HTAP cluster
        run: |
          cd devtools/htap-setup-mysql/proxysql
          docker compose up -d --wait
          sleep 10

      - name: Verify HTAP setup
        run: |
          # Save stats before SELECT
          mysql -h127.0.0.1 -P16032 -uradmin -pradmin --batch --raw -e "SELECT hostname, port, Queries FROM stats.stats_proxysql_servers_metrics;" | tee stats_before.csv

          # Execute READ statement
          mysql -h127.0.0.1 -P16033 -ulol -plol -e "SELECT * FROM db01.test;"

          # Save stats after SELECT
          mysql -h127.0.0.1 -P16032 -uradmin -pradmin --batch --raw -e "SELECT hostname, port, Queries FROM stats.stats_proxysql_servers_metrics;" | tee stats_after.csv

          # Use DuckDB to check if Queries count increased for the read server
          diff=$(duckdb -c "
            CREATE TABLE before AS SELECT * FROM read_csv_auto('stats_before.csv');
            CREATE TABLE after AS SELECT * FROM read_csv_auto('stats_after.csv');
            SELECT (after.Queries - before.Queries) AS diff
            FROM before JOIN after USING(hostname, port)
            WHERE hostname = 'myduckdb-server';
          " | tail -n 1)

          # Verify that Queries count increased by 1
          if [ "$diff" -eq 1 ]; then
            echo 'HTAP setup verification successful.'
          else
            echo 'HTAP setup verification failed.'
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: |
          cd devtools/htap-setup-mysql/proxysql
          docker compose down