name: Password Auth Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: postgresql-client mysql-client
        version: 1.0

    - name: Install dependencies
      run: |
        go get .

        pip3 install "sqlglot[rs]"

        curl -LJO https://github.com/duckdb/duckdb/releases/latest/download/duckdb_cli-linux-amd64.zip
        unzip duckdb_cli-linux-amd64.zip
        chmod +x duckdb
        sudo mv duckdb /usr/local/bin
  
    - name: Build
      run: go build -v
  
    - name: Start MyDuck Server with password
      run: |
        ./myduckserver --superuser-password=testpass123 &
        sleep 5

    - name: Test PostgreSQL auth
      run: |
        export PGPASSWORD=testpass123
        # Basic connection test
        psql -h 127.0.0.1 -U postgres -d postgres -c "SELECT 1 as test;"
        # Create and query a table
        psql -h 127.0.0.1 -U postgres -d postgres -c "CREATE TABLE test (id int); INSERT INTO test VALUES (42); SELECT * FROM test;"
        # Test wrong password
        ! PGPASSWORD=wrongpass psql -h 127.0.0.1 -U postgres -d postgres -c "SELECT 1"

    - name: Test MySQL auth
      run: |
        # Basic connection test
        mysql -h127.0.0.1 -uroot -ptestpass123 -e "SELECT 1 as test;"
        # Create and query a table
        mysql -h127.0.0.1 -uroot -ptestpass123 -e "CREATE DATABASE IF NOT EXISTS test; USE test; CREATE TABLE t1 (id int); INSERT INTO t1 VALUES (42); SELECT * FROM t1;"
        # Test wrong password
        ! mysql -h127.0.0.1 -uroot -pwrongpass -e "SELECT 1"
