name: Compatibility Test for Postgres

on:
  push:
    branches:
      - main
      - compatibility
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          go get .
          
          pip3 install "sqlglot[rs]"
          pip3 install psycopg2
          
          curl -LJO https://github.com/duckdb/duckdb/releases/download/v1.1.3/duckdb_cli-linux-amd64.zip
          unzip duckdb_cli-linux-amd64.zip
          chmod +x duckdb
          sudo mv duckdb /usr/local/bin
          duckdb -c 'INSTALL json from core'
          duckdb -c 'SELECT extension_name, loaded, install_path FROM duckdb_extensions() where installed'
          
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client bats cpanminus
          
          cd compatibility/pg
          curl -L -o ./java/postgresql-42.7.4.jar https://jdbc.postgresql.org/download/postgresql-42.7.3.jar
          npm install pg
          sudo cpanm DBD::Pg
          sudo gem install pg

      - name: Build
        run: go build -v

      - name: Start MyDuck Server
        run: |
          ./myduckserver &
          sleep 5

      - name: Run the Compatibility Test
        run: |
          bats ./compatibility/pg/test.bats
