name: psql Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: postgresql-client
        version: 1.0

    - name: Install dependencies
      run: |
        go get .

        pip3 install "sqlglot[rs]" pyarrow pandas

        curl -LJO https://github.com/duckdb/duckdb/releases/download/v1.1.3/duckdb_cli-linux-amd64.zip
        unzip duckdb_cli-linux-amd64.zip
        chmod +x duckdb
        sudo mv duckdb /usr/local/bin
        duckdb -c 'INSTALL json from core'
        duckdb -c 'SELECT extension_name, loaded, install_path FROM duckdb_extensions() where installed'

    - name: Build
      run: go build -v
  
    - name: Start MyDuck Server
      run: |
        ./myduckserver &
        sleep 5

    - name: Run the SQL scripts
      run: |
        # for each SQL script in the `pgtest/psql` directory (recursively)
        for f in pgtest/psql/**/*.sql; do
          psql -h 127.0.0.1 -U postgres -d postgres -f $f
        done
